version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - export TZ="Asia/Tokyo"
      - echo Logging in to Amazon ECR...
      # AWSのアカウントIDを取得する
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      # ECRへログインする
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # jar build (with test)
      - chmod +x gradlew
      - ./gradlew clean build
      # ビルドに必要なファイル（jar/cacerts）をコピー
      - cp app/build/libs/*.jar docker/
      - cd docker
      # docker image build
      - docker build -t ${ECR_REPOSITORY_NAME}:latest .
      # タグ付け。切り戻し可能にするため、固有タグとlatestタグを付与する
      - docker tag ${ECR_REPOSITORY_NAME}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest
      - docker tag ${ECR_REPOSITORY_NAME}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      # ECR レポジトリにイメージをプッシュする
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}
